"use client";

import { useState, useTransition } from "react";
import { removeBriefingVisualOptionAction, saveBriefingVisualOptionAction } from "@/app/actions/domain-actions";

export function VisualOptionForm({ questionId, option }: { questionId: string; option?: { id: string; value: string; title: string; description: string | null; imageUrl: string | null; altText: string | null; active: boolean } }) {
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState("");
  return <form action={(formData) => { startTransition(async () => { await saveBriefingVisualOptionAction({ id: option?.id, questionId, value: String(formData.get("value") ?? ""), title: String(formData.get("title") ?? ""), description: String(formData.get("description") ?? "") || null, imageUrl: String(formData.get("imageUrl") ?? "") || null, altText: String(formData.get("altText") ?? "") || null, active: formData.get("active") === "on" }); setMessage("Salvo"); }); }} className="mt-4 space-y-2 border-t border-slate-100 pt-4"><input name="value" defaultValue={option?.value} placeholder="Valor" required className="min-h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /><input name="title" defaultValue={option?.title} placeholder="Título curto" required className="min-h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /><input name="imageUrl" defaultValue={option?.imageUrl ?? ""} placeholder="URL da imagem" className="min-h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /><input name="altText" defaultValue={option?.altText ?? ""} placeholder="Texto alternativo" className="min-h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /><textarea name="description" defaultValue={option?.description ?? ""} placeholder="Descrição opcional" className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" /><label className="flex items-center gap-2 text-xs text-slate-600"><input name="active" type="checkbox" defaultChecked={option?.active ?? true} /> Opção ativa</label><div className="flex items-center gap-3"><button disabled={pending} type="submit" className="min-h-10 rounded-xl bg-blue-600 px-4 text-xs font-semibold text-white">{pending ? "Salvando…" : "Salvar opção"}</button>{option ? <button type="button" onClick={() => startTransition(async () => { await removeBriefingVisualOptionAction(option.id); setMessage("Removido; atualize a página."); })} className="text-xs font-semibold text-rose-600">Remover</button> : null}<span className="text-xs text-emerald-600">{message}</span></div></form>;
}
